
project_id = "zepvfisrhhfzlqflgwzb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "extensions"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[functions]
[functions.create-google-drive]
verify_jwt = false

