// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zepvfisrhhfzlqflgwzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplcHZmaXNyaGhmemxxZmxnd3piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNjkxMzcsImV4cCI6MjA1ODc0NTEzN30.otLa8kQwqz8aFTsCi5GbqYKSwh_JRuo0pSDVuXtTPjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);